---------------------------------------------------
--          Z O N E S        M O D U L E         --
---------------------------------------------------
_.Zones =
{
	m(EASTERN_KINGDOMS, {
		m(DUSKWOOD, {
			["description"] = "Duskwood is located in the southern-central part of Azeroth, south of Elwynn Forest, east of Westfall, west of Deadwind Pass, and north of Stranglethorn Vale. Technically part of the Alliance and under Stormwind's protection, its distance from the mighty fortress and its close proximity to more malevolent forces in the south and east make it a realm of horror.[1] Due to events central to the Scythe of Elune, Duskwood is a cursed, dying land. Beneath the eternal blanket of darkness which gave Duskwood its current name, the Scythe's effects have transformed what was once a beautiful part of Elwynn Forest into a land covered in gnarled trees and inhabited by the hideous undead and extradimensional Worgen, brought along with the black fog hanging over the woods. Ogres moving in from Deadwind Pass have brought up even more problems.\n\nLong betrayed and abandoned by Stormwind, Duskwood is inhabited by a defiant people who still cling to their holdings in the face of overwhelming adversity. On all sides lurk dangerous creatures, from skeletal warriors and ghouls to ferocious worgen and some of the most powerful members of the Defias Brotherhood. The militia of Duskwood, known as the Night Watch, patrol the main thoroughfare and protect Darkshire, wary of anything moving through the shadows.\n\nThe most prominent geographical feature of Duskwood is an ancient and long-dead volcano crater. The crater teems with life, and features one of the Great Trees with a portal leading into the Emerald Dream. The sleeping druids' influence can be seen on the surrounding land, which is cloaked in a twilight quite different from the rest of Duskwood. The woods also feature several abandoned farmsteads, as well as the prominent Raven Hill Cemetery, which holds the graves of the numerous people who have been killed by wild beasts and undead since the darkness fell. ",
		}),
	}),
};